In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns 
import missingno as msno 
import datetime as dt

In [2]:
hotel = pd.read_csv('hotel_bookings.csv')

In [3]:
hotel.head()

hotel  is_canceled  ...  reservation_status  reservation_status_date
0  Resort Hotel            0  ...           Check-Out               2015-07-01
1  Resort Hotel            0  ...           Check-Out               2015-07-01
2  Resort Hotel            0  ...           Check-Out               2015-07-02
3  Resort Hotel            0  ...           Check-Out               2015-07-02
4  Resort Hotel            0  ...           Check-Out               2015-07-03

[5 rows x 32 columns]

In [ ]:
hotel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64  
 12  meal            

In [ ]:
# Print number of missing values
hotel.isna().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company         

In [ ]:
hotel.isna().sum().sum()

129425

In [4]:
for col in hotel.columns:
    if col != 'agent' and col != 'company' :
       hotel.dropna(subset = [col], inplace=True)


In [ ]:
# Print number of missing values
hotel.isna().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               0
babies                                 0
meal                                   0
country                                0
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16004
company         

In [ ]:
#for col in hotel.columns:
#    print(col)
#    print(hotel[col].unique())

In [ ]:
#hotel.info()

In [5]:
mappings = {'July': 7,'August': 8,'September': 9,'October': 10,'November': 11,'December': 12,'January': 1,'February': 2,'March': 3,'April': 4,'May': 5,'June': 6}
hotel['arrival_date_month'] = hotel['arrival_date_month'].replace(mappings)
hotel['arrival_date_month'] = hotel['arrival_date_month'].astype('int')

In [6]:
cols=['arrival_date_year','arrival_date_month','arrival_date_day_of_month']
hotel['arrival_date'] = hotel[cols].apply(lambda x: '-'.join(x.values.astype(str)), axis="columns")

In [7]:
hotel['arrival_date'] = pd.to_datetime(hotel['arrival_date'], format = '%Y-%m-%d')

In [8]:
hotel.drop('arrival_date_year', axis = 1, inplace = True)
hotel.drop('arrival_date_month', axis = 1, inplace = True)
hotel.drop('arrival_date_day_of_month', axis = 1, inplace = True)

In [9]:
hotel['reservation_status_date'] = pd.to_datetime(hotel['reservation_status_date'], format = '%Y-%m-%d')

In [ ]:
#hotel.drop(hotel[hotel['reservation_status_date'] > hotel['arrival_date']].index, inplace = True)

In [10]:
hotel[hotel['reservation_status_date'] > hotel['arrival_date']]

hotel  is_canceled  ...  reservation_status_date  arrival_date
2       Resort Hotel            0  ...               2015-07-02    2015-07-01
3       Resort Hotel            0  ...               2015-07-02    2015-07-01
4       Resort Hotel            0  ...               2015-07-03    2015-07-01
5       Resort Hotel            0  ...               2015-07-03    2015-07-01
6       Resort Hotel            0  ...               2015-07-03    2015-07-01
...              ...          ...  ...                      ...           ...
119385    City Hotel            0  ...               2017-09-06    2017-08-30
119386    City Hotel            0  ...               2017-09-07    2017-08-31
119387    City Hotel            0  ...               2017-09-07    2017-08-31
119388    City Hotel            0  ...               2017-09-07    2017-08-31
119389    City Hotel            0  ...               2017-09-07    2017-08-29

[74044 rows x 30 columns]

In [11]:
hotel['children'] = hotel['children'].astype('int')

In [12]:
hotel.drop_duplicates()

hotel  is_canceled  ...  reservation_status_date  arrival_date
0       Resort Hotel            0  ...               2015-07-01    2015-07-01
1       Resort Hotel            0  ...               2015-07-01    2015-07-01
2       Resort Hotel            0  ...               2015-07-02    2015-07-01
3       Resort Hotel            0  ...               2015-07-02    2015-07-01
4       Resort Hotel            0  ...               2015-07-03    2015-07-01
...              ...          ...  ...                      ...           ...
119385    City Hotel            0  ...               2017-09-06    2017-08-30
119386    City Hotel            0  ...               2017-09-07    2017-08-31
119387    City Hotel            0  ...               2017-09-07    2017-08-31
119388    City Hotel            0  ...               2017-09-07    2017-08-31
119389    City Hotel            0  ...               2017-09-07    2017-08-29

[86940 rows x 30 columns]

In [13]:
hotel['agent'].unique()

array([ nan, 304., 240., 303.,  15., 241.,   8., 250., 115.,   5., 175.,
       134., 156., 243., 242.,   3., 105.,  40., 147., 306., 184.,  96.,
         2., 127.,  95., 146.,   9., 177.,   6., 143., 244., 149., 167.,
       300., 171., 305.,  67., 196., 152., 142., 261., 104.,  36.,  26.,
        29., 258., 110.,  71., 181.,  88., 251., 275.,  69., 248., 208.,
       256., 314., 126., 281., 273., 253., 185., 330., 334., 328., 326.,
       321., 324., 313.,  38., 155.,  68., 335., 308., 332.,  94., 348.,
       310., 339., 375.,  66., 327., 387., 298.,  91., 245., 385., 257.,
       393., 168., 405., 249., 315.,  75., 128., 307.,  11., 436.,   1.,
       201., 183., 223., 368., 336., 291., 464., 411., 481.,  10., 154.,
       468., 410., 390., 440., 495., 492., 493., 434.,  57., 531., 420.,
       483., 526., 472., 429.,  16.,  34., 252., 270.,  47., 114., 301.,
       193., 182., 135., 350., 195., 352., 355., 159., 139., 363., 384.,
       360., 331., 367.,  64.,  78., 406., 163., 41

In [14]:
hotel['company'].unique()

array([ nan, 110., 113., 270., 178., 240., 154., 144., 307., 268.,  59.,
       204., 312., 318.,  94., 174., 274., 195., 223., 317., 281., 118.,
        53., 286.,  12.,  47., 324., 342., 373., 371.,  86.,  82., 218.,
        88.,  31., 397., 392., 405., 331., 367.,  20.,  83., 416.,  51.,
       395., 102.,  34.,  84., 360., 394., 382., 461., 478., 112., 486.,
       421.,   9., 308., 135., 224., 504., 269., 356., 498., 390., 513.,
       203., 263., 477., 521., 169., 515., 445., 337., 251., 428., 292.,
       388., 130., 250., 355., 254., 543., 531., 528., 120.,  81., 116.,
       530., 103.,  62.,  39.,  16.,  61.,  92., 501., 291., 290., 192.,
        43., 465., 287., 297., 207., 437., 165., 329., 272.,  28.,  77.,
       482., 200.,  42., 338., 108.,  72., 246., 319., 146., 159., 380.,
       323., 511., 407., 325., 278.,  80., 403., 399.,  14., 137., 343.,
       346., 347., 349., 289., 351., 353.,  54.,  99., 358., 361., 362.,
       366., 372., 365., 277., 109., 377., 379.,  2

In [15]:
hotel.loc[hotel.agent.isnull(), 'agent'] = 0
hotel.loc[hotel.company.isnull(), 'company'] = 0

In [16]:
hotel.isna().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_week_number          0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
company                           0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status          

In [17]:
hotel.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_week_number',
       'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children',
       'babies', 'meal', 'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', 'arrival_date'],
      dtype='object')

In [18]:
i = 0
for col in hotel.columns :
    print (col, i)
    i+=1

hotel 0
is_canceled 1
lead_time 2
arrival_date_week_number 3
stays_in_weekend_nights 4
stays_in_week_nights 5
adults 6
children 7
babies 8
meal 9
country 10
market_segment 11
distribution_channel 12
is_repeated_guest 13
previous_cancellations 14
previous_bookings_not_canceled 15
reserved_room_type 16
assigned_room_type 17
booking_changes 18
deposit_type 19
agent 20
company 21
days_in_waiting_list 22
customer_type 23
adr 24
required_car_parking_spaces 25
total_of_special_requests 26
reservation_status 27
reservation_status_date 28
arrival_date 29


In [19]:
hotel = hotel.reindex(columns=['hotel', 'lead_time', 'arrival_date_week_number',
       'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children',
       'babies', 'meal', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests','agent',
       'company','reservation_status', 'reservation_status_date', 'arrival_date','country','is_canceled'])

In [20]:
hotel.columns

Index(['hotel', 'lead_time', 'arrival_date_week_number',
       'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children',
       'babies', 'meal', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests', 'agent',
       'company', 'reservation_status', 'reservation_status_date',
       'arrival_date', 'country', 'is_canceled'],
      dtype='object')

In [21]:
i = 0
for col in hotel.columns :
    print (col, i)
    i+=1

hotel 0
lead_time 1
arrival_date_week_number 2
stays_in_weekend_nights 3
stays_in_week_nights 4
adults 5
children 6
babies 7
meal 8
market_segment 9
distribution_channel 10
is_repeated_guest 11
previous_cancellations 12
previous_bookings_not_canceled 13
reserved_room_type 14
assigned_room_type 15
booking_changes 16
deposit_type 17
days_in_waiting_list 18
customer_type 19
adr 20
required_car_parking_spaces 21
total_of_special_requests 22
agent 23
company 24
reservation_status 25
reservation_status_date 26
arrival_date 27
country 28
is_canceled 29


In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,8,9,10,14,15,17,19])], remainder='passthrough')
hotel = np.array(ct.fit_transform(hotel))

In [23]:
hotel[5,:]

array([0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 14, 27, 0, 2, 2, 0, 0,
       0, 0, 0, 0, 0, 98.0, 0, 1, 240.0, 0.0, 'Check-Out',
       Timestamp('2015-07-03 00:00:00'), Timestamp('2015-07-01 00:00:00'),
       'GBR', 0], dtype=object)

In [24]:
np.shape(hotel)

(118898, 70)

In [25]:
hotel[5,65:70]

array(['Check-Out', Timestamp('2015-07-03 00:00:00'),
       Timestamp('2015-07-01 00:00:00'), 'GBR', 0], dtype=object)

In [26]:
X = hotel[:, :65]
y = hotel[:, -1]

In [27]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [28]:
print(y[5])

0


In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [30]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [31]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0, max_iter=150)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=150,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [32]:
y_pred = classifier.predict(X_test)

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[13753  1092]
 [ 3372  5563]]


0.8122792262405383

In [34]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 7, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='uniform')

In [35]:
y_pred = classifier.predict(X_test)

KeyboardInterrupt: ignored

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[13213  1632]
 [ 2532  6403]]


0.8248948696383516

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[14548   297]
 [ 4729  4206]]


0.7886459209419681

In [36]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [37]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[13778  1067]
 [ 3086  5849]]


0.8253574432296047

In [1]:
y1 = hotel[:,69:70]
C = np.concatenate((X, y1), axis=1)

NameError: ignored

In [ ]:
kmeans = KMeans(n_clusters = , init = 'k-means++', random_state = 42)
y_kmeans = kmeans.fit_predict(X)